### ISSUE TITLE
Mainly hello and thanks, but also: option to change the svg background colour?

### ISSUE THREAD

**Issue by timbarrass** [xiaomi7732/FlameGraphNet#8]
Hi Saar - wanted to say thanks for putting this library up on github, I used it for [a simple tool I needed](https://github.com/timbarrass/Flame) and it did the job fine :)

While I'm here I feel I should actually make a request so: wondered if you'd considered adding an option to change the overall background colour for the svg produced.

Cheers again!

**Comment by xiaomi7732** [comment]
Hi @timbarrass Check out <https://www.nuget.org/packages/FlameGraph.Net/1.0.3>. Background can be set by options:

```csharp
FlameGraph newGraph = new(new FlameGraphOptions()
{
    Title = "Hello Flame Graph",
    ...
    BackgroundColor = Color.LightGray, // Set the background for the svg
});
```

And happy new year!
